import turtle

# Create a screen object
screen = turtle.Screen()

# Set the background color
screen.bgcolor("black")  # You can use color names or hex codes

# Create a turtle object
my_turtle = turtle.Turtle()

# Draw something
my_turtle.color("white")
my_turtle.pensize(10)
my_turtle.forward(40)
my_turtle.left(90)
my_turtle.forward(20)
my_turtle.left(90)
my_turtle.forward(20)
my_turtle.right(90)
my_turtle.forward(20)
my_turtle.right(90)
my_turtle.forward(40)
my_turtle.right(90)
my_turtle.forward(60)
my_turtle.right(90)
my_turtle.forward(40)
my_turtle.left(90)
my_turtle.forward(40)
my_turtle.left(90)
my_turtle.forward(60)
my_turtle.left(90)
my_turtle.forward(20)
my_turtle.left(90)
my_turtle.forward(40)
my_turtle.right(180)
my_turtle.forward(40)
my_turtle.left(90)
my_turtle.forward(20)
my_turtle.right(90)
my_turtle.forward(20)
my_turtle.left(90)
my_turtle.forward(20)
my_turtle.left(90)
my_turtle.forward(20)
my_turtle.right(90)
my_turtle.forward(40)
my_turtle.right(90)
my_turtle.forward(40)
my_turtle.left(180)
my_turtle.forward(40)
my_turtle.left(90)
my_turtle.forward(40)
my_turtle.left(90)
my_turtle.forward(20)
my_turtle.left(90)
my_turtle.forward(20)
my_turtle.right(90)
my_turtle.forward(20)
my_turtle.right(90)
my_turtle.forward(60)
my_turtle.right(90)
my_turtle.forward(20)
my_turtle.left(90)
my_turtle.forward(40)

my_turtle.left(90)
my_turtle.forward(40)
my_turtle.left(90)
my_turtle.forward(140)
my_turtle.left(90)
my_turtle.forward(140)
my_turtle.left(90)
my_turtle.forward(140)
my_turtle.left(90)
my_turtle.forward(100)


# Keep the window open
turtle.done()
